Program N06JOAOMACHADO ;
//FEITO POR JOÃO VICTOR MOTA MACHADO

USES TARDENOITE;
VAR REGIS:STRING[60];
    ARQ:TEXT;//NOME LOGICO DO ARQUIVO TIPO TEXTO, JÁ QUE O REGISTRO SERÁ UM STRING[60]
    NUM,ANO:STRING[4];
    DIA,MES,CAR:STRING[2];
    NOME:STRING[35];
    CPF:STRING[11];
    A,B,NI,E,DIAI,MESI,ANOI,CARI:INTEGER;
    CHAVE:BOOLEAN;
    TOTC:INTEGER;//PARA GUARDAR O TOTAL DE CARACTERES
Begin
//QUANDO TRABALHAR COM ARQUIVOS, LIGAR O NOME LÓGICO AO FISICO E ABRIR O ARQUIVO...
//E ABRIMOS O ARQUIVO UTILIZANDO O APPEND
   ASSIGN(ARQ,'ARQUIVO1.TXT');
   APPEND(ARQ);
//VALIDAR O NUMERO
   REPEAT
	  WRITE('NUM=>');
    READLN(NUM);
    VAL(NUM,NI,E);//ENTREGA O STRING NUM E RECEBE OS INTEIROS NI e E
    IF (E<>0)THEN
     WRITELN('CARACTER NAO NUMERICO');
   UNTIL(E=0);
//FIM DA VALIDACAO
   WHILE (NI>0) DO
    BEGIN
//GARANTIR QUE O CAMPO NUM TENHA 4 DIGITOS
     TOTC:=LENGTH(NUM);
     FOR A:=1 TO 4 - TOTC DO//LENGTH(NUM) DEVOLVE O TOTAKL DE CARACTRES NO STRING NUM
      INSERT('0',NUM,1);
		 WRITE('NOM=>');
     READLN(NOME);
     NOME:=UPCASE(NOME);//TRANSFORMA STRING EM MAIUSCULO
//GARANTIR QUE O NOME TENHA 35 CARACTERES
		 TOTC:=LENGTH(NOME);
		 FOR A:=TOTC+1 TO 35 DO
		  INSERT(' ',NOME,TOTC+1);
		  
     WRITE('CPF=>');
     READLN(CPF);
     
     REPEAT
     	WRITE('DIA=>');
     	READLN(DIA);
     	TOTC:=LENGTH(DIA);
     	FOR A:=1 TO 2 - TOTC DO
      	INSERT('0',DIA,1);
    	VAL(DIA,DIAI,E);
      
     	WRITE('MES=>');
     	READLN(MES);
     	TOTC:=LENGTH(MES);
     	FOR A:=1 TO 2 - TOTC DO
      	INSERT('0',MES,1);
     	VAL(MES,MESI,E);
     
     	WRITE('ANO=>');
		 	READLN(ANO);
		 	VAL(ANO,ANOI,E);
		 	
		 	CHAVE:=VALDATA(DIAI,MESI,ANOI);
		 	IF NOT CHAVE THEN
		 		WRITELN('DATA INVÁLIDA, INSIRA NOVAMENTE');
		 UNTIL CHAVE;
			
		 REPEAT
		  WRITE('CARGO=>');
		  READLN(CAR);
		  VAL(CAR,CARI,E);
		  IF (CARI>=1) AND (CARI<=12) THEN
		   BEGIN
		    TOTC:=LENGTH(CAR);
     	  FOR A:=1 TO 2 - TOTC DO
      	 INSERT('0',CAR,1);
      	CHAVE:=TRUE;
       END
      ELSE
				BEGIN
					WRITELN('O CARGO DEVE SER ENTRE 1 E 12!');
					CHAVE:=FALSE;
				END;
		 UNTIL CHAVE;	 
		 		 
		 REGIS:=NUM+NOME+CPF+DIA+MES+ANO+CAR;
		 WRITELN(ARQ,REGIS);
		 
//VALIDAR O NUMERO
     REPEAT
	    WRITE('NUM=>');
      READLN(NUM);
      VAL(NUM,NI,E);//ENTREGA O STRING NUM E RECEBE OS INTEIROS NI e E
      IF (E<>0)THEN
       WRITELN('CARACTER NAO NUMERICO');
     UNTIL(E=0);
//FIM DA VALIDACAO
		END;
	 CLOSE(ARQ);
	 TERMINE; 
End.