Program N07JOAOMACHADO ;
//FEITO POR JOÃO VICTOR MOTA MACHADO

USES TARDENOITE;

VAR ARQ:FILE OF REGIS;
    REG:REGIS;
    VET:VETOR;
    NUMSTRING,CARSTRING:STRING;
    A,B,IND,PFI,TOTAL,OPT:INTEGER;
    
Begin
  ASSIGN(ARQ,'CAND.IND');
  RESET(ARQ);
	WRITELN('ESCOLHA UMA OPÇÃO DE ORDENAÇÃO:');
	WRITELN('1-INSCRIÇÃO  2-ALFABÉTICA  3-CPF  4-CARGO');
	LEIA('', OPT);
  WRITELN;
	WHILE (NOT EOF(ARQ)) DO
   BEGIN
    READ(ARQ,REG);
    IND:=IND+1;
    VET[IND].PF:=PFI;      
    IF (OPT = 1) THEN
    	BEGIN
    		STR(REG.NUM:4, NUMSTRING);
    		VET[IND].CC:=NUMSTRING;
    	END
    ELSE IF (OPT = 2) THEN
    	VET[IND].CC:=REG.NOME
    ELSE IF (OPT = 3) THEN
    	VET[IND].CC:=REG.CPF
    ELSE
			BEGIN
			  STR(REG.CAR, CARSTRING);
			  TOTAL:=LENGTH(CARSTRING);
			  FOR A:= 1 TO 2-TOTAL DO
			  	INSERT('0', CARSTRING, 1);
    		VET[IND].CC:=CARSTRING+REG.NOME; 
			END;
		PFI:=PFI+1;  
   END;
   
  TOTAL:=IND;
  WRITELN('AGUARDE, ORDENANDO...');
	ORDEM(VET,TOTAL);
	WRITELN('');
	WRITELN('PRESSIONE ENTER PARA CONTINUAR');
  FOR B:=1 TO TOTAL DO
	 BEGIN
	  SEEK(ARQ,VET[B].PF);
		READ(ARQ,REG);
    IF((B-1) MOD 25 = 0)THEN
    BEGIN
      READLN;
      CLRSCR;
			WRITELN;
      WRITE('  ORD  NUM N O M E                             ===C P F=== NASCIMENTO CS  N1');
      WRITELN('  N2  N3  N4  N5  N6   SO   CG  CC CV FA');
     END;
		WRITE(B:5,REG.NUM:5,' ',REG.NOME,' ',REG.CPF,' ',REG.DATA.DIA,'/',REG.DATA.MES,'/',REG.DATA.ANO,REG.CAR:3);
		FOR A:=1 TO 6 DO
		 WRITE(REG.NOTAS[A]:4);
		WRITELN(REG.SOM:5,REG.CLG:5,REG.CLC:4,REG.CCL:3,REG.FALTA:3);
	 END;
	TERMINE;
End.