Program N08JOAOMACHADO;
//FEITO POR: JOÃO VICTOR MOTA MACHADO

USES TARDENOITE;

CONST DISCIPLINAS:ARRAY [1..6] OF STRING[20]=
('L.E.M              ','MATEMÁTICA         ','LÓGICA             ',
'CONHECIMENTO ESPEC.','INFORMÁTICA        ','ATUALIDADES        ');

VAR
 ARQ:FILE OF REGIS;
 REG:REGIS;
 NOTA:TEXT;
 VET:VETOR;
 A,B,C,POSIV,II,TOT,TC,TT,CAND:INTEGER;
 MEDIA:ARRAY [1..6] OF REAL;
 NOTAINT,SOMANOTA:ARRAY [1..6] OF INTEGER;
 NOTASTR:ARRAY [1..6] OF STRING[4];
 NUMA,NUM:STRING[4];
BEGIN
 ASSIGN(ARQ,'CAND.IND');
 ASSIGN(NOTA,'NOTAS.TXT');
 RESET(ARQ);
 RESET(NOTA);
 REPEAT
  READ(ARQ,REG);
  II:=A+1;          
	VET[II].PF:=A;    
	STR(REG.NUM,NUM);
	TC:=LENGTH(NUM);
	FOR B:=1 TO 4-TC DO
	 INSERT('0',NUM,1);  
	VET[II].CC:=NUM; 
	A:=A+1;
 UNTIL(EOF(ARQ));	
 TOT:=II;
 WRITELN(' AGUARDE, ORDENANDO E CALCULANDO MÉDIAS...');
 ORDEM(VET,II); 
 
 //ATUALIZAR AS NOTAS
 REPEAT
  TT:=TT+1;
  READLN(NOTA,NUMA,NOTASTR[1],NOTASTR[2],NOTASTR[3],NOTASTR[4],NOTASTR[5],NOTASTR[6]);
  PEBIN1(VET,NUMA,TOT,POSIV);                      
  SEEK(ARQ,VET[POSIV].PF);
  READ(ARQ,REG);
  REG.SOM:=0;
   FOR A:=1 TO 6 DO
  	 BEGIN
  	  VAL(NOTASTR[A], NOTAINT[A], C);
			REG.NOTAS[A]:=NOTAINT[A];	
			SOMANOTA[A]:=SOMANOTA[A]+NOTAINT[A];		 
			REG.SOM:=REG.SOM+REG.NOTAS[A];
  	 END;  	
  SEEK(ARQ,VET[POSIV].PF);
	WRITE(ARQ,REG);
 UNTIL EOF(NOTA);
 
 
//CALCULO DA MEDIA
 FOR A:=1 TO 6 DO
  MEDIA[A]:=SOMANOTA[A]/TT;

 WRITELN(' ENTER PARA CONTINUAR');
 READLN;
 WRITELN;
 TEXTCOLOR(WHITE);
 WRITELN('DISCIPLINA                MÉDIA'); 
 WRITELN;
 FOR A:=1 TO 6 DO
  Begin
   WRITELN(DISCIPLINAS[A],MEDIA[A]:12:2);
	End;
 WRITELN;
 TERMINE; 
CLOSE(NOTA);
CLOSE(ARQ);
END.