Program N09JOAOMACHADO;
//FEITO POR: JOÃO VICTOR MOTA MACHADO

USES TARDENOITE;

CONST CARGOS:ARRAY [1..12] OF STRING[21]=
('ENGANADOR DE CHEFE    ','ENROLADOR DE TRABALHO ',
 'PENSADOR              ','ANALISTA DE SISTEMAS  ',
 'DEGUSTADOR DE CERVEJA ','TECNICO EM REDES      ',
 'CONTADOR DE ESTORIAS  ','PEDREIRO DE PRIMEIRA  ',
 'ACOUGUEIRO LIMPINHO   ','SEGURANCA DE BANHEIRO ',
 'GESTOR DE BORBOLETAS  ','AGENTE LEVA E TRAZ    ');

VAR
 ARQ:FILE OF REGIS;
 REG:REGIS;
 VAGAS:TEXT;
 VET:VETOR;
 NUMVAGAS,CLAS,CARTOT:ARRAY[1..12] OF INTEGER;
 LINHA:ARRAY[1..12] OF STRING[32];
 NOTASTR:ARRAY [1..6] OF STRING[4];
 A,II,TOT,CAR,DATAINT,ERR:INTEGER;
 DATAINV:STRING[8];
 JUNTA:STRING[4];
 DATASTR:STRING[6];
  
Begin
 ASSIGN(ARQ,'CAND.IND');
 ASSIGN(VAGAS,'VAGAS.TXT');
 RESET(ARQ);
 RESET(VAGAS);
 
 FOR A:=1 TO 12 DO
  BEGIN
   READLN(VAGAS,LINHA[A]);
   VAL(COPY(LINHA[A],30,2),NUMVAGAS[A],ERR);
  END;
 
 WHILE (NOT EOF(ARQ)) DO
  BEGIN
   READ(ARQ,REG);
   II:=II+1;
   VET[II].PF:=II-1;
   DATAINV:=REG.DATA.ANO+REG.DATA.MES+REG.DATA.DIA;
   VAL(DATAINV,DATAINT,ERR);
   DATAINT:=20200101-DATAINT;
   STR(DATAINT,DATASTR);
   FOR A:=1 TO 6 DO
    STR(REG.NOTAS[A],NOTASTR[A]);
	 STR(REG.SOM,JUNTA);
	 VET[II].CC:=JUNTA+NOTASTR[4]+NOTASTR[5]+NOTASTR[3]+NOTASTR[2]+NOTASTR[6]+NOTASTR[1]+DATASTR;  
  END;
 TOT:=II;
 WRITELN('ATUALIZANDO OS CAMPOS DE CLASSIFICAÇÃO...');
 ORDEM(VET,TOT);
 II:=0;
 FOR A:=TOT DOWNTO 1 DO
  BEGIN
   II:=II+1;
   SEEK(ARQ,VET[A].PF);
   READ(ARQ,REG);
   CAR:=REG.CAR;
   CLAS[CAR]:=CLAS[CAR]+1;
   REG.CLC:=CLAS[CAR];
   REG.CLG:=II;
   IF(CLAS[CAR]<=NUMVAGAS[CAR]) THEN
    BEGIN
     REG.CCL:=CAR;
     CARTOT[REG.CAR]:=CARTOT[REG.CAR]+1;
    END;
   SEEK(ARQ,VET[A].PF);
   WRITE(ARQ,REG);
  END;
 CLRSCR;
 WRITELN(II,' REGISTROS LIDOS');
 WRITELN('');
 TEXTCOLOR(WHITE);
 WRITELN('OS CAMPOS DE CLASSIFICAÇÃO FORAM ATUALIZADOS!!!');
 WRITELN('');    
 TERMINE;
 CLOSE(ARQ);
 CLOSE(VAGAS);  
End.