Program N10JOAOMACHADO;
//FEITO POR: JOÃO VICTOR MOTA MACHADO

USES TARDENOITE;

VAR
 ARQ:FILE OF REGIS;
 REG:REGIS;
 VAGAS:TEXT;
 VET:VETOR;
 A,ANT,COUNT,ERR,TOT,IND,OPT:INTEGER;
 CARSTR,CLCSTR,CLGSTR,CCLSTR:STRING[4];
 NUMV:ARRAY[1..12] OF INTEGER;
 LINHA:ARRAY[1..12] OF STRING[32];
 

Begin
 ASSIGN(ARQ,'CAND.IND');
 ASSIGN(VAGAS,'VAGAS.TXT');
 RESET(ARQ);
 RESET(VAGAS);
 COUNT:=0;
 
 WRITELN(' ESCOLHA UMA OPÇÃO DE ORDENAÇÃO: ');
 WRITELN;
 WRITELN('(1) CANDIDATOS CLASSIFICADOS EM CADA CARGO - ORDEM ALFABÉTICA');
 WRITELN('(2) CANDIDATOS EM ORDEM DE CLASSIFICAÇÃO POR CARGO');
 WRITELN('(3) CANDIDATOS EM ORDEM DE CLASSIFICAÇÃO GERAL');
 WRITELN;
 REPEAT
  BEGIN
   WRITE(' INSIRA UMA OPÇÃO ENTRE 1 E 3 ');
   LEIA('',OPT);
   IF (OPT<1) OR (OPT>3) THEN
    WRITELN(' OPCÃO INVALIDADA');
  END;
 UNTIL (OPT>=1) AND (OPT<4);

 WHILE NOT(EOF(ARQ)) DO
  BEGIN
   READ(ARQ,REG);
   COUNT:=COUNT+1;
   IF(OPT=1) THEN
    BEGIN
     IF(REG.CCL>0)THEN
      BEGIN
       IND:=IND+1;
       VET[IND].PF:=COUNT-1;
       STR(REG.CCL:4,CCLSTR);
       VET[IND].CC:=CCLSTR+REG.NOME;
      END;
		END
		ELSE IF(OPT=2) THEN
		 BEGIN
		  VET[COUNT].PF:=COUNT-1;
		  STR(REG.CAR:4,CARSTR);
		  INSERT(CARSTR,VET[COUNT].CC,1);
		  STR(REG.CLC:4,CLCSTR);
		  INSERT(CLCSTR,VET[COUNT].CC,5);
		 END
		ELSE IF(OPT=3) THEN
		 BEGIN
		  VET[COUNT].PF:=COUNT-1;
		  STR(REG.CLG:4,CLGSTR);
		  VET[COUNT].CC:=CLGSTR
		 END
  END;
 
 WRITELN;
 WRITELN(' AGUARDE, ORDENANDO...');
 WRITELN;
 IF(OPT=1) THEN
  COUNT:=IND;
 ORDEM(VET,COUNT);
 TOT:=COUNT;
 COUNT:=0;
 WRITELN;
 WRITELN(' PRESSIONE ENTER PARA CONTINUAR');

 FOR A:= 1 TO 12 DO
  BEGIN
   READLN(VAGAS,LINHA[A]);
   VAL(COPY(LINHA[A],30,2),NUMV[A],ERR);
  END;

 FOR A:=1 TO TOT DO
  BEGIN
	 SEEK(ARQ,VET[A].PF);
	 READ(ARQ,REG);
	  IF((COUNT MOD 25)=0) OR (ANT <> REG.CAR) AND (OPT<3) THEN
		 BEGIN
		  READLN;
			CLRSCR;
			WRITELN;
			IF(OPT<3) THEN
			 BEGIN                              
			  WRITELN('    CURSO ',REG.CAR:2,' -> ',COPY(LINHA[REG.CAR],3,25));
				WRITELN;
				IF(OPT=1) THEN
				 WRITELN('    ORD NUM NOME                                NASCIMENTO CAR');
			 END
			ELSE
			 BEGIN
			  WRITELN('   ORDEM DE CLASSIFICACAO GERAL');
				WRITELN;
		   END;
			IF(OPT>1) THEN
			 WRITELN('   ORD  NUM NOME			    	SOM  N4  N5  N3  N2  N6  N1 NASCIMENTO CAR  OBSERVACAO');
			IF(ANT <> REG.CAR) AND (OPT<3) THEN
			 COUNT:=0;
			ANT:=REG.CAR;
	 	 END;	
		COUNT:=COUNT+1;
		IF(OPT=1) THEN
		 WRITELN(COUNT:6,REG.NUM:5,' ',REG.NOME,' ',REG.DATA.DIA,'/',REG.DATA.MES,'/',REG.DATA.ANO,REG.CAR:3)
		ELSE
		 BEGIN
		  WRITE(COUNT:6,REG.NUM:5,' ',REG.NOME,REG.SOM:4,REG.NOTAS[4]:4,REG.NOTAS[5]:4,REG.NOTAS[3]:4,REG.NOTAS[2]:4,
			REG.NOTAS[6]:4,REG.NOTAS[1]:4,' ',REG.DATA.DIA,'/',REG.DATA.MES,'/',REG.DATA.ANO,REG.CAR:3,' ');
			IF(REG.CCL>0) THEN
			 WRITELN(' CLAS CAR = ', REG.CCL)
			ELSE
			 WRITELN;
		 END;
	END;
 CLOSE(ARQ);
 CLOSE(VAGAS);
 WRITELN;
 TERMINE;  
End.